spring:
  datasource:
    url: jdbc:postgresql://postgres_database:5432/starwars_db
    username: ${POSTGRESQL_USER:postgres}
    password: ${POSTGRESQL_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true

management:
  endpoints:
    web:
      exposure:
        include: "*"